name: Install and Build
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      
      - name: Get Unity Version
        id: get_version
        run: |
          $match = [regex]::match((Get-Content -Path ProjectSettings\ProjectVersion.txt | Out-String), 'm_EditorVersionWithRevision: (?<version>[^\s]+) \((?<changeset>[^\)]+)\)')
          echo "VERSION=$($match.groups["version"].Value)" >> $env:GITHUB_OUTPUT
          echo "CHANGESET=$($match.groups["changeset"].Value)" >> $env:GITHUB_OUTPUT
             
      - name: Install Unity
        run: |
          echo "Downloading Hub Installer"
          curl --output installer.exe "https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe"
          echo "Installing Hub"
          & ".\installer.exe" /S | Out-Default
          echo "Installing Editor"
          & "C:/Program Files/Unity Hub/Unity Hub.exe" -- --headless install --version $env:UNITY_VERSION --changeset $env:UNITY_CHANGESET | Out-Default
          echo "Installing Modules"
          & "C:/Program Files/Unity Hub/Unity Hub.exe" -- --headless install-modules --version $env:UNITY_VERSION --module $env:MODULE --childModules | Out-Default
        env:
          UNITY_VERSION: ${{ steps.get_version.outputs.VERSION }}
          UNITY_CHANGESET: ${{ steps.get_version.outputs.CHANGESET }}
          MODULE: android
          
      - name: Activate Unity License
        run: |
          & "$env:UNITY_PATH" -username $env:UNITY_EMAIL -serial $env:UNITY_SERIAL -password $env:UNITY_PASSWORD -logFile - -nographics -batchmode -quit | Out-Default
        env: 
          UNITY_PATH: C:\Program Files\Unity\Hub\Editor\${{ steps.get_version.outputs.VERSION }}\Editor\Unity.exe
          UNITY_SERIAL: ${{ secrets.UNITY_SERIAL }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
      
      - name: Build Project
        run:  |
          & "$env:UNITY_PATH" -executeMethod $env:BUILD_METHOD -batchmode -quit -logFile - | Out-Default
        env: 
          UNITY_PATH: C:\Program Files\Unity\Hub\Editor\${{ steps.get_version.outputs.VERSION }}\Editor\Unity.exe
          BUILD_METHOD: Builder.BuildAndroidPlayer
      
      - name: Return Unity License
        if: always() 
        run: |
          & "$env:UNITY_PATH" -returnlicense -logFile - -verbose -nographics -batchmode -quit | Out-Default
        env: 
          UNITY_PATH: C:\Program Files\Unity\Hub\Editor\${{ steps.get_version.outputs.VERSION }}\Editor\Unity.exe
